import Button from "components/Button";

// In a real world scenario this would be a dynamic component generated by the component name/id (in this casse Button)
function Preview() {
  const Component = Button;
  return (
    <section>
      <h2>Component Preview</h2>
      <Component
        variant="contained"
        fullWidth={true}
        size="large"
        color="primary"
      />
    </section>
  );
}

export default Preview;
